"""Verification for InsightFace-issued model licenses."""

from .model_license import (
    LICENSE_FILENAME,
    STATUS_DEFAULT_NON_COMMERCIAL,
    STATUS_DEPENDENCY_MISSING,
    STATUS_EXPIRED,
    STATUS_INVALID,
    STATUS_INVALID_MANIFEST,
    STATUS_NOT_ACTIVE,
    STATUS_VERIFIED_COMMERCIAL,
    STATUS_VERIFIED_NON_COMMERCIAL,
    ModelLicense,
    ModelLicenseDependencyError,
    ModelLicenseError,
    ModelLicenseExpiredError,
    ModelLicenseInspection,
    ModelLicenseManifestError,
    ModelLicenseNotActiveError,
    canonical_license_bytes,
    inspect_model_license,
    inspect_model_package_license,
    verify_model_license,
)

__all__ = [
    "LICENSE_FILENAME",
    "ModelLicense",
    "ModelLicenseDependencyError",
    "ModelLicenseError",
    "ModelLicenseExpiredError",
    "ModelLicenseInspection",
    "ModelLicenseManifestError",
    "ModelLicenseNotActiveError",
    "STATUS_DEFAULT_NON_COMMERCIAL",
    "STATUS_DEPENDENCY_MISSING",
    "STATUS_EXPIRED",
    "STATUS_INVALID",
    "STATUS_INVALID_MANIFEST",
    "STATUS_NOT_ACTIVE",
    "STATUS_VERIFIED_COMMERCIAL",
    "STATUS_VERIFIED_NON_COMMERCIAL",
    "canonical_license_bytes",
    "inspect_model_license",
    "inspect_model_package_license",
    "verify_model_license",
]
